# spec/spec_helper.rb

# This file was generated by the `rails generate rspec:install` command.
# It contains configuration for RSpec itself, not tied to Rails.

RSpec.configure do |config|
  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  # Use the specified formatter
  config.default_formatter = "doc" if config.files_to_run.one?

  # Print the 10 slowest examples and example groups at the end of the spec run
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Seed global randomization using the `--seed` CLI option
  Kernel.srand config.seed

  # Enable warnings to help identify potential issues
  config.warnings = true

  # Configure expectation syntax
  config.expect_with :rspec do |expectations|
    # Enable chaining of custom matcher descriptions
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # Configure mocking framework
  config.mock_with :rspec do |mocks|
    # Verify that methods being mocked or stubbed actually exist
    mocks.verify_partial_doubles = true
  end

  # Allow shared context metadata to be inherited by host groups
  config.shared_context_metadata_behavior = :apply_to_host_groups
end
